---
deployment:
  tasks:
    - /bin/cp -R .cpanel-artifacts/main/. $HOME/public_html/
    - /bin/mkdir -p $HOME/public_html/premium-travel
    - /bin/cp -R .cpanel-artifacts/premium-travel/. $HOME/public_html/premium-travel/
